#!/bin/sh
echo "Type a word"
read word
echo $word is $(echo -n $word | wc -c) letters long
echo or $word is ${#word} letters long
------------------

for file in *
do
if [ ! -d $file ] #ie: if $file isn’t a directory
then
echo "wc $file ownerID, permisions, size, date are"
wc $file
else
echo "$file is a directory"
fi
done
--------

#!/bin/bash
OS=`uname -s`
if [ “$OS” = “FreeBSD” ]; then
echo “This Is FreeBSD”
elif [ “$OS” = “CYGWIN_NT-5.1” ]; then
echo “This is Cygwin”
elif [ “$OS” = “SunOS” ]; then
echo “This is Solaris”
elif [ “$OS” = “Darwin” ]; then
echo “This is Mac OSX”
elif [ “$OS” = “AIX” ]; then
echo “This is AIX”
elif [ “$OS” = “Minix” ]; then
echo “This is Minix” 
elif [ “$OS” = “Linux” ]; then
echo “This is Linux”
else
echo “Failed to identify this OS”
fi
---------------
if [ $# -eq 0 ]
then
     echo "$0 : You must give/supply one integers"
     exit 1
fi
if test $1 -gt 0
then
     echo "$1 number is positive"
else
     echo "$1 number is negative"
fi
---------------
#!/bin/bash
if [ -z $1 ]
then
     rental="*** Unknown vehicle ***"
elif [ -n $1 ]
then
# otherwise make first arg as rental
     rental=$1
fi
case $rental in
     "car") echo "For $rental Rs.20 per k/m";;
     "van") echo "For $rental Rs.10 per k/m";;
     "jeep") echo "For $rental Rs.5 per k/m";;
     "bicycle") echo "For $rental 20 paisa per k/m";;
     *) echo "Sorry, I can not gat a $rental for you";;
esac
-------------
#!/bin/bash
hostname
uname
whoami
who
pwd
ps –e
top
logout
