#!/bin/sh
echo "Type a word"
read word
echo $word is $(echo -n $word | wc -c) letters long
echo or $word is ${#word} letters long
------------------

for file in *
do
if [ ! -d $file ] #ie: if $file isn’t a directory
then
echo "wc $file ownerID, permisions, size, date are"
wc $file
else
echo "$file is a directory"
fi
done
--------

#!/bin/bash
OS=`uname -s`
if [ “$OS” = “FreeBSD” ]; then
echo “This Is FreeBSD”
elif [ “$OS” = “CYGWIN_NT-5.1” ]; then
echo “This is Cygwin”
elif [ “$OS” = “SunOS” ]; then
echo “This is Solaris”
elif [ “$OS” = “Darwin” ]; then
echo “This is Mac OSX”
elif [ “$OS” = “AIX” ]; then
echo “This is AIX”
elif [ “$OS” = “Minix” ]; then
echo “This is Minix” 
elif [ “$OS” = “Linux” ]; then
echo “This is Linux”
else
echo “Failed to identify this OS”
fi
---------------
if [ $# -eq 0 ]
then
     echo "$0 : You must give/supply one integers"
     exit 1
fi
if test $1 -gt 0
then
     echo "$1 number is positive"
else
     echo "$1 number is negative"
fi
---------------
#!/bin/bash
if [ -z $1 ]
then
     rental="*** Unknown vehicle ***"
elif [ -n $1 ]
then
# otherwise make first arg as rental
     rental=$1
fi
case $rental in
     "car") echo "For $rental Rs.20 per k/m";;
     "van") echo "For $rental Rs.10 per k/m";;
     "jeep") echo "For $rental Rs.5 per k/m";;
     "bicycle") echo "For $rental 20 paisa per k/m";;
     *) echo "Sorry, I can not gat a $rental for you";;
esac
-------------
#!/bin/bash
hostname
uname
whoami
who
pwd
ps –e
top
logout
---------------------
#!/bin/bash
# Example 0 : While loop. Keeping looping while i is less than 10
# The first line creates a variable. Note that to read a
# variable you need to put a ’$’ before its name
i=0
while [ $i -lt 10 ]
do
echo i is $i
let i=$i+1
done
-----------------
#!/bin/bash
# example 2: For Loop.
# Do a letter, word and line count of all the files in
# the current directory.
# The ‘*’ below is expanded to a list of files. The
# variable ‘file’ successively takes the value of
# these filenames. Preceding a variable name by ‘$’
# gives its value.
for file in *
do
echo "wc $file gives"
wc $file
done
------------------
colors[1]=red
colors[2]=green
colors[3]=blue
echo The array colors has ${#colors[*]} elements.
echo They are ${colors[*]}
--------
#!/bin/sh
times=$(who | grep $1 | wc -l)
echo "$1 is logged on $times times."
------------
for file in $*
do
if [ -d $file ]
then
10
ls $file
fi
done

