#!/bin/bash
for (( i=1; i<=4; i++ ))
do
  for (( j=1; j<=i; j++ ))
  do
   echo -n "$j"
   done
   echo ""
done




------


number=1
rows=5
for((i=1; i<=rows; i++))
do
  for((j=1; j<=i; j++))
  do
    echo -n "$number "
    number=$((number + 1))
  done
  number=1
  echo
done



echo "Enter the size of numbers(N)"
read N

i=1
max=0

echo "Enter the numbers"
while [ $i -le $N ]
do
  read num
  if [ $i -eq 1 ] 
  then
      max=$num
  else             
      if [ $num -gt $max ]
      then
        max=$num
      fi
  fi
  i=$((i + 1))  
done
